#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TeamEferns.Droid.Resource", IsApplication=true)]

namespace TeamEferns.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int categoryList = 2131099666;
			
			// aapt resource value: 0x7f060000
			public const int chkList = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int currentLocationLabel = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int currentLocationView = 2131099664;
			
			// aapt resource value: 0x7f06000d
			public const int emailLabel = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int emailView = 2131099662;
			
			// aapt resource value: 0x7f060003
			public const int eventDate = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int eventList = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int eventLocation = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int eventName = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int firstNameLabel = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int firstNameView = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int forgttext = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int lastNameLabel = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int lastNameView = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int lmainlogo = 2131099654;
			
			// aapt resource value: 0x7f060011
			public const int preferenceText = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int save = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int signin = 2131099656;
			
			// aapt resource value: 0x7f060005
			public const int toplay3 = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CategoryListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int EventDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int EventList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int EventListView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Preferences = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
